dataset: "nights"        # which dataset's inference to run (nights, nod, things)
img_dir: "/home/wallacelab/teba/multimodal_brain_inspired/dreamsim/dreamsim/nights"    # root directory for inference image dataset
batch_size: 128

inference_save_dir: "/home/wallacelab/teba/multimodal_brain_inspired/marren/temporal_dynamics_of_human_alignment/test/cliphba_baseline_seed1"
backbone : "ViT-L/14"
vision_layers: 2
transformer_layers: 1
rank: 32
cuda: 1 #(device selector):
model_weights_path: "/home/wallacelab/teba/multimodal_brain_inspired/marren/temporal_dynamics_of_human_alignment/test/cliphba_baseline_seed1"

num_workers: 4 # (for THINGS/NOD extraction, defaults to 8)
load_hba: true