dataset: "nights"        # which dataset's inference to run (nights, nod, things)
inference_image_dir: "/path/to/NIGHTS"    # root directory for inference image dataset
index_file: "/path/to/index.csv" # CSV mapping images to categories for the inference image dataset
nights_split: "test"                   # dataset split if using NIGHTS
things_stimuli_csv: "/path/to/things_stimuli.csv"  # stimuli metadata for THINGS (if using things)
things_concept_index: "/path/to/things_concepts.npy" # concept index if needed
batch_size: 256


backbone: "ViT-L/14"
load_hba: true
model_weights: "/home/wallacelab/teba/multimodal_brain_inspired/marren/temporal_dynamics_of_human_alignment/test/cliphba_baseline_seed1/checkpoint.pth"